modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="drstone"
version="1.0.0"
displayName="DrStone"
authors="Dragone"
description='''
Mod DrStone
'''

[[dependencies.drstone]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.drstone]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"
